# Generated by Django 3.2.8 on 2021-11-18 05:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='analogs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
