# Generated by Django 3.2.5 on 2021-07-23 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_auto_20210723_1450'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='calls',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='calls.calls'),
        ),
    ]
