# Generated by Django 3.2.5 on 2021-08-03 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210803_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='supermanager',
        ),
    ]
