# Generated by Django 3.2.5 on 2021-08-06 10:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_supermanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='neg_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), null=True, size=None),
        ),
    ]
