# Generated by Django 3.2.5 on 2021-08-06 10:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_neg_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='neg_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), default=list, size=None),
        ),
    ]
