# Generated by Django 3.2.5 on 2021-08-06 11:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_neg_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pos_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='customuser',
            name='scripts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), default=list, size=None),
        ),
    ]
