# Generated by Django 3.2.5 on 2021-08-16 04:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210806_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='parazits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='neg_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pos_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='scripts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), default=list, null=True, size=None),
        ),
    ]
