# Generated by Django 3.2.5 on 2021-08-17 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210816_0459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='parazits',
            new_name='par_words',
        ),
    ]
