# Generated by Django 3.2.5 on 2021-08-22 05:34

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_parazits_customuser_par_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='neg_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='par_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pos_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='scripts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=list, max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='supermanager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
