# Generated by Django 3.2.5 on 2021-08-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210830_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='critical',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='podstr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='purity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
