# Generated by Django 3.2.5 on 2021-08-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210830_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='critical',
            field=models.CharField(blank=True, default='‒', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='podstr',
            field=models.CharField(blank=True, default='‒', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='purity',
            field=models.CharField(blank=True, default='‒', max_length=255),
        ),
    ]
