# Generated by Django 3.2.5 on 2021-08-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210830_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='critical',
            field=models.CharField(default='‒', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='podstr',
            field=models.CharField(default='‒', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='purity',
            field=models.CharField(default='‒', max_length=255),
        ),
    ]
