# Generated by Django 3.2.5 on 2021-09-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210831_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='uploaded_amount',
            field=models.IntegerField(default=0),
        ),
    ]
