# Generated by Django 3.2.5 on 2021-09-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210902_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
