# Generated by Django 3.2.6 on 2021-09-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_customuser_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
