# Generated by Django 3.2.6 on 2021-09-13 16:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='neg_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), blank=True, default=['щас', 'че', 'э', 'ээ', 'эээ', 'аа', 'ааа', 'ниче', 'типа', 'ну', 'мм', 'ммм', 'скока', 'нискока', 'скоко', 'нискоко', 'але', 'здрасьте'], size=None),
        ),
    ]
