# Generated by Django 3.2.6 on 2021-09-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_customuser_neg_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='critical_hints_count_all',
            field=models.CharField(default='‒', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='critical_hints_count_avg',
            field=models.CharField(default='‒', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='critical_interception_all',
            field=models.CharField(default='‒', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='critical_interception_avg',
            field=models.CharField(default='‒', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='critical_loud_podstr',
            field=models.CharField(default='‒', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='critical_negative_emotions',
            field=models.CharField(default='‒', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='critical_negative_words_all',
            field=models.CharField(default='‒', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='critical_negative_words_avg',
            field=models.CharField(default='‒', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='critical_script_following',
            field=models.CharField(default='‒', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='critical_speech_purity',
            field=models.CharField(default='‒', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='critical_speech_volume',
            field=models.CharField(default='‒', max_length=255),
        ),
    ]
