# Generated by Django 3.2.6 on 2021-09-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20210915_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='critical_speed_podstr',
            field=models.CharField(default='‒', max_length=255),
        ),
    ]
