# Generated by Django 3.2.6 on 2021-09-21 05:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20210917_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='client_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), blank=True, default=list, size=None),
        ),
    ]
