# Generated by Django 3.2.6 on 2021-09-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_customuser_client_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(default='‒', max_length=255),
        ),
    ]
