# Generated by Django 3.2.6 on 2021-09-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='script_following',
            field=models.CharField(default='‒', max_length=255),
        ),
    ]
