# Generated by Django 3.2.6 on 2021-09-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20210929_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='client_words',
            new_name='client_pos_words',
        ),
    ]
