# Generated by Django 3.2.8 on 2021-10-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_customuser_client_neg_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='critical_critical_words_all',
            field=models.CharField(default='‒', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='critical_critical_words_avg',
            field=models.CharField(default='‒', max_length=255),
        ),
    ]
