# Generated by Django 3.2.8 on 2021-10-21 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20211013_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='department',
            new_name='department_old',
        ),
    ]
