# Generated by Django 3.2.8 on 2021-10-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_name'),
        ('users', '0045_customuser_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='product',
        ),
        migrations.AddField(
            model_name='customuser',
            name='product',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
