# Generated by Django 3.2.8 on 2021-10-29 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_auto_20211027_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department_old',
        ),
    ]
