# Generated by Django 3.2.8 on 2021-11-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_remove_customuser_department_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='podstr',
        ),
        migrations.AddField(
            model_name='customuser',
            name='loud_podstr',
            field=models.CharField(default='‒', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='speed_podstr',
            field=models.CharField(default='‒', max_length=255),
        ),
    ]
