# Generated by Django 3.2.8 on 2021-11-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_auto_20211108_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='crit_words_count',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='neg_client',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='neg_operator',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='neg_words_count',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pos_client',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pos_operator',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
