# Generated by Django 3.2.8 on 2021-11-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_auto_20211110_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hide_critical_words',
            field=models.BooleanField(default=False),
        ),
    ]
