# Generated by Django 3.2 on 2021-07-12 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='call',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calls.call'),
        ),
    ]
