# Generated by Django 3.2.5 on 2021-07-23 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_calls'),
        ('calls', '0003_auto_20210723_1450'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Call',
        ),
    ]
