# Generated by Django 3.2.5 on 2021-07-24 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_calls'),
        ('calls', '0004_delete_call'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calls',
            new_name='Call',
        ),
    ]
