# Generated by Django 3.2.5 on 2021-07-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_rename_calls_call'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='advices_given',
        ),
        migrations.RemoveField(
            model_name='call',
            name='emotions',
        ),
        migrations.RemoveField(
            model_name='call',
            name='interruptions',
        ),
        migrations.RemoveField(
            model_name='call',
            name='mandatory_question',
        ),
        migrations.RemoveField(
            model_name='call',
            name='script_matching',
        ),
        migrations.RemoveField(
            model_name='call',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='call',
            name='stop_words',
        ),
        migrations.RemoveField(
            model_name='call',
            name='text',
        ),
        migrations.RemoveField(
            model_name='call',
            name='volume_vector',
        ),
    ]
