# Generated by Django 3.2.5 on 2021-07-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0007_call_start_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advices',
        ),
        migrations.DeleteModel(
            name='MandatoryQuestions',
        ),
        migrations.DeleteModel(
            name='Records',
        ),
        migrations.DeleteModel(
            name='StopWords',
        ),
        migrations.AlterField(
            model_name='call',
            name='record',
            field=models.FileField(upload_to='media/records/', verbose_name='Запись'),
        ),
    ]
