# Generated by Django 3.2.5 on 2021-07-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0008_auto_20210725_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='record',
            field=models.FileField(upload_to='records/', verbose_name='Запись'),
        ),
    ]
