# Generated by Django 3.2.5 on 2021-08-03 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0010_auto_20210803_0548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='userId',
            new_name='user',
        ),
    ]
