# Generated by Django 3.2.5 on 2021-08-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0011_rename_userid_call_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='record',
            field=models.FileField(upload_to='records/'),
        ),
        migrations.AlterField(
            model_name='call',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
