# Generated by Django 3.2.5 on 2021-08-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0012_auto_20210803_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='salt',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
