# Generated by Django 3.2.5 on 2021-08-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0013_call_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='salt',
        ),
        migrations.AlterField(
            model_name='call',
            name='record',
            field=models.FileField(upload_to='records/Qcnlp572kGKObTOggOrSc./'),
        ),
    ]
