# Generated by Django 3.2.5 on 2021-08-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0014_auto_20210805_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='record',
            field=models.FileField(upload_to='records/SwiykuDumv1NvWSxPce67u/'),
        ),
    ]
