# Generated by Django 3.2.5 on 2021-08-28 00:06

import calls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0026_alter_call_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='record',
            field=models.FileField(upload_to=calls.models.UploadTo('records')),
        ),
    ]
