# Generated by Django 3.2.5 on 2021-08-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0027_auto_20210828_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='freq_hints',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='interseptions',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='podstr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='purity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='volume',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
