# Generated by Django 3.2.5 on 2021-08-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0028_auto_20210831_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='freq_hints',
            field=models.CharField(default='‒', max_length=255),
        ),
        migrations.AlterField(
            model_name='call',
            name='interseptions',
            field=models.CharField(default='‒', max_length=255),
        ),
        migrations.AlterField(
            model_name='call',
            name='podstr',
            field=models.CharField(default='‒', max_length=255),
        ),
        migrations.AlterField(
            model_name='call',
            name='purity',
            field=models.CharField(default='‒', max_length=255),
        ),
        migrations.AlterField(
            model_name='call',
            name='volume',
            field=models.IntegerField(default=100),
        ),
    ]
