# Generated by Django 3.2.5 on 2021-09-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0030_alter_call_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
