# Generated by Django 3.2.6 on 2021-09-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0033_auto_20210913_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(default='Обработано', max_length=255),
        ),
    ]
