# Generated by Django 3.2.6 on 2021-09-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0034_alter_call_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='freq_hints',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='call',
            name='podstr',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='call',
            name='purity',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
