# Generated by Django 3.2.6 on 2021-09-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0035_auto_20210913_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(default='Обработка', max_length=255),
        ),
    ]
