# Generated by Django 3.2.6 on 2021-09-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0037_call_critical'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='interseptions',
            new_name='interceptions',
        ),
    ]
