# Generated by Django 3.2.6 on 2021-09-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0038_rename_interseptions_call_interceptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='script_following',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
