# Generated by Django 3.2.6 on 2021-09-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0039_call_script_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='reverse',
            field=models.BooleanField(default=False),
        ),
    ]
