# Generated by Django 3.2.8 on 2021-11-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0040_call_reverse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='podstr',
        ),
        migrations.AddField(
            model_name='call',
            name='loud_podstr',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='call',
            name='speed_podstr',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
