# Generated by Django 3.2.8 on 2021-11-10 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0043_auto_20211110_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='crit_words',
            new_name='crit_words_count',
        ),
        migrations.RenameField(
            model_name='call',
            old_name='neg_words',
            new_name='neg_words_count',
        ),
    ]
