# Generated by Django 3.2.8 on 2021-11-10 09:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0044_auto_20211110_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='client_neg_words_said',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='call',
            name='client_pos_words_said',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='call',
            name='crit_words_said',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='call',
            name='neg_words_said',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='call',
            name='par_words_said',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
