# Generated by Django 3.2.8 on 2021-11-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0046_auto_20211111_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='client_neg_words_said',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='call',
            name='client_pos_words_said',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='call',
            name='crit_words_said',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='call',
            name='neg_words_said',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='call',
            name='par_words_said',
            field=models.JSONField(default=dict),
        ),
    ]
