# Generated by Django 3.2.8 on 2021-11-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0047_auto_20211111_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='script_statistics',
            field=models.JSONField(default=dict),
        ),
    ]
