# Generated by Django 3.2.8 on 2021-11-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0050_auto_20211123_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='debug_time_wa_arrived_again',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='debug_time_wa_sent_again',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
