# Generated by Django 3.2.8 on 2021-11-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0051_auto_20211123_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='debug_time_daiml_spent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='debug_time_wa_spent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='debug_time_wa_spent_again',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
