# Generated by Django 3.2.8 on 2021-11-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0052_auto_20211123_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
