# Generated by Django 3.2.8 on 2021-11-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0053_call_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='debug_time_uploaded_spent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
