# Generated by Django 3.2.8 on 2021-11-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0054_call_debug_time_uploaded_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='debug_time_daiml_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='debug_time_daiml_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
