# Generated by Django 3.2.6 on 2021-10-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='script',
            options={'verbose_name': 'Скрипт', 'verbose_name_plural': 'Скрипты'},
        ),
        migrations.AddField(
            model_name='script',
            name='department',
            field=models.CharField(default='Не задан', max_length=255),
        ),
    ]
