# Generated by Django 3.2.6 on 2021-10-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_auto_20211005_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
