# Generated by Django 3.2.6 on 2021-10-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_script_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='product',
            field=models.CharField(default='Основной', max_length=255),
        ),
    ]
