# Generated by Django 3.2.8 on 2021-10-21 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('scripts', '0004_script_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='product',
            new_name='product_old',
        ),
        migrations.AddField(
            model_name='script',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
