# Generated by Django 3.2.8 on 2021-10-21 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_name'),
        ('scripts', '0005_auto_20211021_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
