# Generated by Django 3.2.8 on 2021-10-21 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0006_auto_20211021_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='department',
            new_name='department_old',
        ),
    ]
