# Generated by Django 3.2.8 on 2021-10-21 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_alter_department_name'),
        ('scripts', '0007_rename_department_script_department_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department'),
        ),
    ]
