# Generated by Django 3.2.8 on 2021-11-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0010_auto_20211029_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
