# Generated by Django 3.2.8 on 2021-11-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='balance_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='balance_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
