# Generated by Django 3.2.8 on 2021-11-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20211111_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='uploaded_amount',
            field=models.IntegerField(default=0),
        ),
    ]
