const managers = [
    {
        id: 3,
        rating: '10.0',
        first_name: 'Тест',
        last_name: 'Тестов',
        critical: '1',
        purity: '93%',
        speed_podstr: '55%',
        loud_podstr: '86%',
        script_following: '‒',
        count: 2,
        color: 0,
        avatar: '/static/images/avatar.svg',
        status: true,
        department: 'Не задан',
        product: ['Не задан'],
    },
    {
        id: 55,
        rating: '5.0',
        first_name: 'Вячеслав',
        last_name: 'Щербинин',
        critical: '1',
        purity: '93%',
        speed_podstr: '45%',
        loud_podstr: '84%',
        script_following: '‒',
        count: 2,
        color: 2,
        avatar: '/static/images/avatar.svg',
        status: true,
        department: 'Не задан',
        product: ['Не задан'],
    },
    {
        id: 141,
        rating: '7.6',
        first_name: 'Алла',
        last_name: 'Анголова',
        critical: '3',
        purity: '95%',
        speed_podstr: '100%',
        loud_podstr: '100%',
        script_following: '27%',
        count: 9,
        color: 1,
        avatar: '/static/images/avatar.svg',
        status: true,
        department: 'Администратор',
        product: ['Не задан'],
    },
    {
        id: 142,
        rating: '‒',
        first_name: 'Алина',
        last_name: 'Гизатулина',
        critical: '‒',
        purity: '‒',
        speed_podstr: '‒',
        loud_podstr: '‒',
        script_following: '‒',
        count: 0,
        color: 0,
        avatar: '/static/images/avatar.svg',
        status: true,
        department: 'Администратор',
        product: ['Не задан'],
    },
];
export default managers;
