# Generated by Django 3.2.8 on 2021-11-18 05:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dictionary_name', models.TextField(null=True)),
                ('dictionary_words', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), blank=True, default=list, size=None)),
            ],
            options={
                'verbose_name': 'Словарь',
                'verbose_name_plural': 'Словари',
            },
        ),
    ]
