# Generated by Django 3.2.8 on 2021-11-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='dictionary_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
