# Generated by Django 3.2.8 on 2021-11-18 05:30

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_alter_dictionary_dictionary_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='dictionary_words',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(null=True), blank=True, default=list, size=None),
        ),
    ]
